Repository microsoft/quantum-viz.js, pull requests merged in 2022-05, with the labels that each got.

#55 Fix horizontal scrolling issue
  src/sqore.ts
Labels: bug

#56 Fix incorrect zoom button sign when collapse parent operation
  src/sqore.ts
Labels: bug

#60 Fix zoom button rendering when `ConditionalRender.AsGroup`
  __tests__/process.test.ts
  src/process.ts
Labels: bug

#61 Allow overflowed SVGs scroll-able and restructure `index.html`
  example/index.html
  example/script.js
Labels: enhancement

#44 Add a full-featured serializer from a `qiskit.QuantumCircuit` to a `quantum-viz.js` JSON
  .gitignore
  quantum-viz/README.md
  quantum-viz/examples/Qiskit.ipynb
  quantum-viz/examples/display_example.py
  quantum-viz/noxfile.py
  quantum-viz/poetry.lock
  quantum-viz/pyproject.toml
  quantum-viz/quantum_viz/qiskit_parser.py
  quantum-viz/quantum_viz/utils.py
  quantum-viz/quantum_viz/widget.py
  quantum-viz/tests/conftest.py
  quantum-viz/tests/resources/conditioned_ops_qc.json
  quantum-viz/tests/resources/empty_circ.json
  quantum-viz/tests/resources/no_ops_qc.json
  quantum-viz/tests/resources/no_ops_regs_qc.json
  quantum-viz/tests/resources/parametrized_qc.json
  quantum-viz/tests/resources/simple_qc.json
  quantum-viz/tests/test_qiskit_parser.py
  quantum-viz/tests/test_widget.py
Labels: hacktoberfest-accepted
